version: '3.8'

services:
  game-backend:
    container_name: game-backend
    build:
      context: ./
      target: dev
    volumes:
      - "./:/usr/src/"
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"

  game-mongodb:
    image: mongo:5.0
    container_name: game-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  game-mongo-express:
    image: mongo-express
    container_name: game-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@game-mongodb
